### PR TITLE
mingw fixes (not only) for Windows

### PR DESCRIPTION
**Pull request by dg0yt**
This restores the VCPKG_CROSSCOMPILING change which was authored by you in vcpkg PR 18927, and fixes the actual issues for mingw:
- The system name is "windows" not "mingw". Fixes the DLL binary names.
- Omit `''` from list of standard libraries. Fixes native build failures.

Would be glad if you would pick this up for you PR.

Tested with harfbuzz:x64-mingw-dynamic on Windows.

### CODE REVIEW

**Comment by autoantwort** [comment]
I think the real problem for the native windows builds is that no host compiler is set. Before this change windows -> windows was no cross compilation, now it is, but fribidi want's to build something on the host system and no host compiler is set. Befor this change this was not a problem because it was no cross build

**Comment by dg0yt** [comment]
I restored your VCPKG_CROSSCOMPILING change (without VCPKG_TARGET_IS_MINGW), so my non-cross mingw build is a native meson build again.

**Comment by autoantwort** [comment]
Yeah but the `x86-windows-*` and all the other windows triplets that are not `x64-windows` are now not native any more

**Comment by dg0yt** [comment]
I see. Well then you have to rollback that line. It is your original work. It is not relevant for mingw.

**Comment by autoantwort** [comment]
Maybe be can add an AND condition with `VCPKG_CROSSCOMPILING`, so `(... OR VCPKG_TARGET_IS_MINGW) AND VCPKG_CROSSCOMPILING`

**Comment by dg0yt** [comment]
On a second look on CPU architecture, it is fragile to rely on matching names in `BUILD_CPU_FAM MATCHES "${HOST_CPU_FAM}"` to cover x86 on x64 (aka x86_64) or arm on arm64 build machine, unless designed that way by meson.
The explicit solution would be setting a list variable with native-compatible build machines for each target CPU.

**Comment by autoantwort** [comment]
Or you then always use cross compiling and set the host compiler. But the you need get_cmake_vars for the host triplet

**Comment by dg0yt** [comment]
| host tripet | target triplet | VCPKG_CROSSCOMPILING | meson cross |
|-----------------|----------|----------|----------|
| x86-windows |  x86-windows | no | no |
| x64-windows |  x86-windows | YES | **no** |
| x64-mingw |  x86-mingw | YES | YES |
| x64-mingw |  x64-mingw | no | no |
| x64-linux |  x86-mingw | YES| YES|
|                 | android | YES| YES|
|                 | ios | YES| YES|

What about macOS arm vs x64?

**Comment by autoantwort** [comment]
What do you mean with the `meson cross` column?

**Comment by dg0yt** [comment]
`meson cross` was meant to indicate whether a cross configuration is mandatory for meson.

> Or you then always use cross compiling and set the host compiler. But the you need get_cmake_vars for the host triplet

Ports that really need host's get_cmake_vars for meson might be required to have a host dependency on some port that provides that information.

**Comment by dg0yt** [comment]
> Maybe be can add an AND condition with `VCPKG_CROSSCOMPILING`, so `(... OR VCPKG_TARGET_IS_MINGW) AND VCPKG_CROSSCOMPILING`

For now, the mildest change for mingw is looking at `WIN32`:

~~~
 if(NOT BUILD_CPU_FAM MATCHES "${HOST_CPU_FAM}" OR VCPKG_TARGET_IS_ANDROID OR VCPKG_TARGET_IS_IOS OR VCPKG_TARGET_IS_UWP OR (VCPKG_TARGET_IS_MINGW AND NOT WIN32))

**Comment by autoantwort** [comment]
For x64 on arm mac it seems that no cross config is needed. I don't have a intel mac to test the other way (and don't want to read the documentation 😅). 

> Ports that really need host's get_cmake_vars for meson might be required to have a host dependency on some port that provides that information.

But for example the fribidi don't support setting a host dependency, you must provide a host compiler 

> For now, the mildest change for mingw is looking at WIN32

Ok then I will use that

**Pull request merged**
